
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/aidanjost/.opam/5.1.0/bin/"
      - "/Users/aidanjost/.juliaup/bin/"
      - "/Users/aidanjost/v/"
      - "/Users/aidanjost/zls/zig-out/bin/"
      - "/opt/homebrew/opt/gcc/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/aidanjost/bin/"
      - "/opt/homebrew/opt/gnu-sed/libexec/gnubin/"
      - "/opt/homebrew/opt/coreutils/libexec/gnubin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/aidanjost/.config/nvm/versions/node/v20.19.2/bin/"
      - "/Users/aidanjost/.swiftly/bin/"
      - "/Users/aidanjost/.elan/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/aidanjost/.cargo/bin/"
      - "/Users/aidanjost/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/"
      - "/opt/homebrew/opt/fzf/bin/"
    searched_directories:
      - "/Users/aidanjost/.opam/5.1.0/bin/uname"
      - "/Users/aidanjost/.juliaup/bin/uname"
      - "/Users/aidanjost/v/uname"
      - "/Users/aidanjost/zls/zig-out/bin/uname"
      - "/opt/homebrew/opt/gcc/bin/uname"
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/Users/aidanjost/bin/uname"
      - "/opt/homebrew/opt/gnu-sed/libexec/gnubin/uname"
    found: "/opt/homebrew/opt/coreutils/libexec/gnubin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/aidanjost/.opam/5.1.0/bin"
        - "/Users/aidanjost/.juliaup/bin"
        - "/Users/aidanjost/v"
        - "/Users/aidanjost/zls/zig-out/bin"
        - "/opt/homebrew/opt/gcc/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/aidanjost/bin"
        - "/Users/aidanjost/bin"
        - "/opt/homebrew/opt/gnu-sed/libexec/gnubin"
        - "/opt/homebrew/opt/coreutils/libexec/gnubin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/aidanjost/.juliaup/bin"
        - "/Users/aidanjost/.config/nvm/versions/node/v20.19.2/bin"
        - "/Users/aidanjost/.opam/5.1.0/bin"
        - "/Users/aidanjost/v"
        - "/Users/aidanjost/zls/zig-out/bin"
        - "/opt/homebrew/opt/gcc/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/aidanjost/bin"
        - "/opt/homebrew/opt/gnu-sed/libexec/gnubin"
        - "/opt/homebrew/opt/coreutils/libexec/gnubin"
        - "/Users/aidanjost/.swiftly/bin"
        - "/Users/aidanjost/.elan/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/aidanjost/.cargo/bin"
        - "/Users/aidanjost/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        - "/opt/homebrew/opt/fzf/bin"
